server:

  urouting:
    default-content-type: "application/json"

  db:
    datasources:
      default:
        jdbc-url: "jdbc:mysql://localhost/guism?serverTimezone=UTC"
        username: "root"
        password: "admin"
        log-query-execution-longer-than-ms: 500
        pool-max-size: 10
        driver-class-name: com.mysql.cj.jdbc.Driver